"""change userId to user_id in quizzes table

Revision ID: a95bae22220b
Revises: f4c2d59118e9
Create Date: 2023-08-15 22:32:11.163320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95bae22220b'
down_revision: Union[str, None] = 'f4c2d59118e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('quizzes_userId_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'])
    op.drop_column('quizzes', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_userId_fkey', 'quizzes', 'users', ['userId'], ['id'])
    op.drop_column('quizzes', 'user_id')
    # ### end Alembic commands ###
