"""Initial migration

Revision ID: e4eaa6b3dbd3
Revises: 
Create Date: 2023-08-14 22:10:29.775235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4eaa6b3dbd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sa.String(), nullable=True),
    sa.Column('article_title', sa.String(), nullable=True),
    sa.Column('paragraph_num', sa.String(), nullable=True),
    sa.Column('item_num', sa.Float(), nullable=True),
    sa.Column('item_title', sa.String(), nullable=True),
    sa.Column('sentense_text', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('correct_choice', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizzes')
    op.drop_table('users')
    op.drop_table('laws')
    # ### end Alembic commands ###
